# Generated by Django 2.0 on 2019-09-01 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyWritingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(help_text='Hero Header', max_length=255)),
                ('hero_lead', models.CharField(help_text='Hero Lead Text', max_length=255)),
                ('hero_cta_text', models.CharField(help_text='Hero CTA Text', max_length=255)),
                ('hero_cta_url', models.URLField(help_text='Hero CTA Text', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
