# Generated by Django 2.0 on 2019-09-01 13:41

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_copywritingsettings_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copywritingsettings',
            name='testimonial',
            field=wagtail.core.fields.StreamField((('row', wagtail.core.blocks.StreamBlock((('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())))),), blank=True, null=True),
        ),
    ]
