# Generated by Django 3.0.7 on 2020-06-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CopyWritingSettings',
        ),
    ]
