version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    volumes:
      - staticfiles:/app/static
      - mediafiles:/app/media
    ports:
      - 80:80
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: ./compose/production/web/Dockerfile
    image: wagtail_site_prod_web
    command: /start
    volumes:
      - staticfiles:/app/static
      - mediafiles:/app/media
    env_file:
      - ./.env/.prod-sample
    environment:
        - RECAPTCHA_PRIVATE_KEY
        - RECAPTCHA_PUBLIC_KEY
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=wagtail_site
      - POSTGRES_USER=wagtail_site
      - POSTGRES_PASSWORD=wagtail_site

volumes:
  postgres_data:
  staticfiles:
  mediafiles:
