version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/web/Dockerfile
    image: wagtail_blog_web
    command: /start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=wagtail_blog
      - POSTGRES_USER=wagtail_blog
      - POSTGRES_PASSWORD=wagtail_blog

volumes:
  postgres_data:
