# Generated by Django 4.1 on 2023-05-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0012_alter_blogpage_body_alter_postpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpage',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='search_image',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='tags',
        ),
        migrations.AlterUniqueTogether(
            name='postpageblogcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postpageblogcategory',
            name='blog_category',
        ),
        migrations.RemoveField(
            model_name='postpageblogcategory',
            name='page',
        ),
        migrations.RemoveField(
            model_name='postpagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='postpagetag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='PostPage',
        ),
        migrations.DeleteModel(
            name='PostPageBlogCategory',
        ),
        migrations.DeleteModel(
            name='PostPageTag',
        ),
    ]
