# Generated by Django 4.1 on 2023-05-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('site', '0013_remove_postpage_header_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPage',
            new_name='SitePage',
        ),
    ]
