# Generated by Django 4.1 on 2023-06-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0017_socialmediasettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
