# Generated by Django 4.1 on 2023-06-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0018_alter_socialmediasettings_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='twitter',
        ),
    ]
