# Generated by Django 4.1 on 2023-06-25 18:15

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0019_remove_socialmediasettings_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='static_content',
            field=wagtail.fields.StreamField([('h1', wagtail.blocks.CharBlock()), ('h2', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='code')), ('testimonials', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(required=False)), ('name', wagtail.blocks.RichTextBlock(required=False))]))), ('image_text', wagtail.blocks.StructBlock([('reverse', wagtail.blocks.BooleanBlock(required=False)), ('title', wagtail.blocks.RichTextBlock(required=False)), ('text', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('image_carousel', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('thumbnail_gallery', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))], blank=True, use_json_field=True),
        ),
    ]
