# Generated by Django 4.1 on 2023-06-25 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0001_squashed_0020_formpage_static_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formpage',
            old_name='static_content',
            new_name='body',
        ),
    ]
