# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('blog', '0004_postpage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
