# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 12:53
from __future__ import unicode_literals

from django.db import migrations
import wagtailmd.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postpage_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtailmd.utils.MarkdownField(),
        ),
    ]
