# Generated by Django 3.0.7 on 2020-06-20 07:58

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180614_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='excerpt',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='excerpt'),
        ),
    ]
