# Generated by Django 3.0.7 on 2020-06-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200620_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpage',
            name='excerpt',
        ),
    ]
